routes:

  /safari/: safari
  /safari/northern-tanzania-safari/: northern-tanzania-safari
  /trekking/: trekking
  /daytrips/: daytrips
  /contact/: contact
  /about/: about

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
