routes:

  /safari/: safari
  /trekking/: trekking
  /daytrips/: daytrips
  /contact/: contact
collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
